### ISSUE TITLE
index out of range [0]

### ISSUE THREAD

**Issue by Madic-** [aleroyer/rsyslog_exporter#2]
Hello,

when using the rpm release on a centos 7 system, I'm getting the following error:
rsyslog version: v8.24.0-52.el7

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
flag.init()
	/opt/hostedtoolcache/go/1.13.10/x64/src/flag/flag.go:1007 +0x176
rsyslogd: Child 28715 has terminated, reaped by main-loop. [v8.24.0-52.el7 try http://www.rsyslog.com/e/0 ]
```

Do you need further information?

**Comment by sreerajkksd** [comment]
You are talking about rsyslog rpm or rsyslog_exporter RPM ? Can you add some sample rsyslog configurations ?

**Comment by Madic-** [comment]
I am sorry but I'm not able to reproduce the problem. Maybe it came because the rsyslog_exporter was compiled on a different system. But I've changed our build process and the exporter is now build on the same system it's going to run. I'll close the ticket

**Comment by nike38rus** [comment]
For those folks who suffered from this error as bad as me. There is a bug in rsyslog versions prior 8.32.0: https://github.com/rsyslog/rsyslog/issues/1858. It leads to panic when exporter tries to parse CLI arguments with `flag` package that relies on binary name being set and doesn't check its existence.
> argv[0] not set when using binary without arguments
When using the omprog plugin with a binary without arguments, argv[0] (the name of the binary) is not set, causing binaries that depend on this value being set to crash or misbehave.

There are two solutions:
1. Upgrade rsyslog to 8.32.0 or newer
2. Pass any argument (among supported) as binary parameter, even with default value
```
  action(
    type="omprog"
    name="to_exporter"
    binary="/usr/local/bin/rsyslog_exporter -web.listen-address :9104"
  )
